DROP DATABASE IF EXISTS wii_code;

CREATE DATABASE wii_code;

\connect wii_code

CREATE TABLE UserObj (
	ID SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE Project (
	ID SERIAL PRIMARY KEY,
	ownerId INTEGER NOT NULL,
	projectName VARCHAR(255) NOT NULL,
	lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	directory VARCHAR(512),
	CONSTRAINT Project_FK FOREIGN KEY (ownerId) REFERENCES UserObj(ID)
);

CREATE TABLE File (
	ID SERIAL PRIMARY KEY,
	content BYTEA NOT NULL,
	fileName VARCHAR(255),
	lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	project INTEGER NOT NULL,
	CONSTRAINT File_FK FOREIGN KEY (project) REFERENCES Project(ID)
);
